### ISSUE TITLE
C Port

### ISSUE THREAD

**Issue by bkgoodman** [ShellAddicted/ESP32Servo#1]
I made a port of this to straight "C" - didn't know how/if you might want to include. (Didn't want to do it as a PR because it undoes your C++ code - maybe I should do in a separate directory?) I didn't want to break the ability to easily include as a submodule...

[https://github.com/bkgoodman/ESP32Servo](https://github.com/bkgoodman/ESP32Servo)

**Comment by ShellAddicted** [comment]
Hi, thanks for your interest, as far as I know, there's no easy way to do that without fully rewriting my cpp code.That's why I think that keeping the repos separate is the best solution at the moment.

I wrote this for personal use, but then released it because it may help others playing with servos, and being C compatible was not in my requirements list.

If you want to make a c/cpp compatible idf-component, you may add a `#ifdef __cplusplus` conditioned `extern 'C'` statement to your fork.
